name: Update Plugins
on:
  workflow_dispatch:
    inputs:
      update-submodules:
        type: boolean
        default: "false"
        description: Update Submodules
      sync-plugin:
        type: boolean
        default: "false"
        description: Sync Common Files
      update-readme:
        type: boolean
        default: "false"
        description: Update Readme
      update-doc:
        type: boolean
        default: "false"
        description: Update Doc
      submodules-https:
        type: boolean
        default: "false"
        description: Update Submodules to HTTPS
      build-plugin:
        type: boolean
        default: "false"
        description: Build Plugin Test

jobs:
  update:
    strategy:
      matrix:
        repo: 
          - plugin-seed
          - ble
          - gps
          - gesturehandler
          - https
          - ui-collectionview
          - algolia
          - perms
          - sensors
          - ui-pager
          - ui-drawer
          - ui-document-picker
          - ui-material-components
          - ui-persistent-bottomsheet
          - ui-carto
          - universal-links
          - ui-mapbox
          - ui-webview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone component repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
        repository: nativescript-community/${{ matrix.repo }}
        path: ${{ matrix.repo }}
    - name: Set yarn cache directory
      id: yarn-cache
      working-directory: ${{ matrix.repo }}
      run: echo "RESULT=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
    - name: Cache node modules
      id: lerna-yarn-cache
      if: ${{ ( matrix.repo  != 'plugin-seed') && (github.event.inputs.update-readme == 'true' || github.event.inputs.update-doc == 'true') }}
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
          path: |
              ${{ steps.yarn-cache.outputs.RESULT }}
              **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
    - name: Install dependencies if needed.
      if: ${{ (matrix.repo != 'plugin-seed') && ((github.event.inputs.update-readme == 'true') || (github.event.inputs.update-doc == 'true')) && (steps.lerna-yarn-cache.outputs.cache-hit != 'true') }}
      working-directory: ${{ matrix.repo }}
      run: yarn add --cached
    - name: Update Submodules
      if: github.event.inputs.update-submodules == 'true'
      id: submodules
      run: |
        ./update-submodules.sh ${{ matrix.repo }}
    
    - name: Sync Common Files
      if: github.event.inputs.sync-plugin == 'true'
      run: |
        ./sync.sh ${{ matrix.repo }}
    - name: Update Readme
      if: ${{ (matrix.repo != 'plugin-seed') && (github.event.inputs.update-readme == 'true') }}
      run: |
        ./update_readme.sh ${{ matrix.repo }}
    - name: Update Doc
      if: ${{ (matrix.repo != 'plugin-seed') && (github.event.inputs.update-doc == 'true') }}
      run: |
        ./update_doc.sh ${{ matrix.repo }}
    - name: Update Submodules to HTTPS
      if: ${{ (github.event.inputs.submodules-https == 'true') }}
      run: |
        ./update_submodules_https.sh ${{ matrix.repo }}
    - name: Build Plugin Test
      if: ${{ (matrix.repo != 'plugin-seed') && (github.event.inputs.build-plugin == 'true') }}
      run: |
        ./build.sh ${{ matrix.repo }}
